//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace License1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public int id { get; set; }
        public string licensekey { get; set; }
        public int num_days { get; set; }
        public int num_hours { get; set; }
        public int num_times { get; set; }
        public Nullable<System.DateTime> activation_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string installed_machine { get; set; }
        public string installed_user { get; set; }
    }
}
